### ISSUE TITLE
no rows in result set

### ISSUE THREAD

**Issue by taobaohi** [blockloop/scan#12]
rows, _ := db.Query("SELECT * FROM persons where name = 'brett' LIMIT 1")
var person Person
// if rows.Count==0
err := scan.Row(&person, rows)
// err:sql: no rows in result set

**Comment by taobaohi** [comment]
if err == sql.ErrNoRows{
    //...........
}

**Comment by blockloop** [comment]
Can you provide a reproducible test or some more details?
