### ISSUE TITLE
bug:scan.Values(userCols, &user) is slice but  need a arry

### ISSUE THREAD

**Issue by schmath** [blockloop/scan#24]
sq.Insert(userCols...).
        Into("users").
        Values(scan.Values(userCols, &user)...).RunWith(db).Exec()
err converting argument $1 type: unsupported type []interface {}, a slice of interface
scan.Values(userCols, &user) return a slice of interface,but args ...interface{} is a arry interface.

**Comment by blockloop** [comment]
@schmath I'm not sure I understand this bug. Can you provide a complete main.go file?
