### ISSUE TITLE
Extract JSON field as a nested struct

### ISSUE THREAD

**Issue by JC1738** [blockloop/scan#50]
Awesome library.  Is there any support for JSON fields and the ability to extract those into a struct?

**Comment by blockloop** [comment]
Do you mean to support reading the `json` tag as opposed to the `db` tag?

**Comment by blockloop** [comment]
@JC1738 if you can give more detail I'll try to help

**Comment by blockloop** [comment]
I'm closing this issue. If you have any more info feel free to post back and I'll re-open.
