### ISSUE TITLE
Calling `Row` does not autoclose

### ISSUE THREAD

**Issue by trojanc** [blockloop/scan#52]
When calling `scan.Row()` it does not autoclose the rows as `scan.Rows()` does.
Is this intentional? I now end up having to add `defer rows.Close()` everywhere I used `scan.Row()`

**Comment by blockloop** [comment]
Everything flows through `rows` at some point. So scan.Row eventually does call close [here](https://github.com/blockloop/scan/blob/1a405331637adb6d9dc2b705a41c4e48b3d12a56/scanner.go#L60)

**Comment by blockloop** [comment]
There is an oversight on my part though. I should move up the call to the
entrypoint of the libarary because it's possible to panic before it reaches
this `close` which would leave it open and cause a leak. I'll send a PR shortly.
