### ISSUE TITLE
Memory leak in scan.columns and scan.values

### ISSUE THREAD

**Issue by max-stytch** [blockloop/scan#61]
The `&sync.Map{}` cache mechanism used in `columns.go` and `values.go` caches individual instances of structs, not the "kind" of struct. This causes memory leaks in long-running applications that call `scan.Columns` or `scan.Values` on many different struct instances.

```golang
// PrintMemUsage outputs the current, total and OS memory being used. As well as the number
// of garage collection cycles completed.
func PrintMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// For info on each, see: https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
}
func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}

type MyObject struct {
	Value string "db:value"
}

func TestMemoryLeak(t *testing.T) {
	PrintMemUsage()
	for i := 0; i < 1e6; i++ {
		obj := &MyObject{Value: "Some value goes here"}
		cols, err := scan.ColumnsStrict(obj)
		if err != nil {
			t.Fail()
		}
		_, err = scan.Values(cols, obj)
		if err != nil {
			t.Fail()
		}
	}
	runtime.GC()
	PrintMemUsage()
}
```

outputs
```
=== RUN   TestMemoryLeak
Alloc = 4 MiB	TotalAlloc = 7 MiB	Sys = 18 MiB	NumGC = 3
Alloc = 503 MiB	TotalAlloc = 724 MiB	Sys = 619 MiB	NumGC = 13
--- PASS: TestMemoryLeak (2.45s)
PASS
```

Additionally, the debugger shows the columns cache map contains 100k objects.
<img width="365" alt="image" src="https://github.com/blockloop/scan/assets/89937743/44188c6d-473b-429b-8c41-0bb665177747">

Suggest either
- changing the cache key to something that is consistent across different instances of the same struct
- removing the cache mechanism entirely (we aren't even hitting the cache unless `scan.Columns` is called on the same instance multiple times)

**Comment by blockloop** [comment]
Fixed in v2.2.0
